# Generated by Django 3.2.7 on 2021-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210916_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_ac',
            field=models.CharField(max_length=20),
        ),
    ]
